worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include C:/nginx-1.29.8/conf/mime.types;
    default_type application/octet-stream;

    sendfile on;

    keepalive_timeout 65;

    map $uri $valid_region {
        default 0;
        "~/routes/(?i)salt-lake$" 1; # Weird stuff for case-insensitivty after the (?i)
        "~/routes/(?i)skyline$" 1;
        "~/routes/(?i)provo$" 1;
        "~/routes/(?i)uintas$" 1;
        "~/routes/(?i)ogden$" 1;
        "~/routes/(?i)logan$" 1;
        "~/routes/(?i)moab$" 1;
        "~/routes/(?i)abajos$" 1;
        "~/routes/(?i)southwest$" 1;
    }

    server {
        listen       80;
        server_name  localhost;
        root   "C:/Users/ka7nq/webProjects/avyBuddy/src/main/web";
        index  index.html;

        location / {
            try_files $uri $uri/ $uri.html =404;
        }

        location /routes/ { # Checks end of url path for routes to see if it is valid, 404s if not
                            # valid paths determined by the mapping above
            error_page 404 /routes404.html;

            if ($valid_region = 0){
                return 404;
            }

            rewrite ^ /routes.html;
        }

        location /route/ {
            rewrite ^ /routeDetail.html;
        }

        location /account/ {
            rewrite ^ /accountDetail.html;
        }

        location /apis/ {
            proxy_pass http://127.0.0.1:8080/;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}
